name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/TrabalhoFinal/
            
            # Garante que estamos com a última versão do repositório
            git pull

            # Cria o arquivo .env com base no secret do GitHub
            echo "${{ secrets.LARAVEL_ENV }}" > .env

            # Se quiser usar o .env.example, pode ser assim também:
            # cp .env.example .env
            
            # Para os containers se estiverem rodando
            docker compose down

            # Sobe os containers com build e já usando o novo .env
            docker compose up -d --build

            # Roda comandos Laravel dentro do container
            docker compose exec app php artisan migrate --force
            docker compose exec app php artisan optimize:clear
            docker compose exec app php artisan config:cache
            docker compose exec app php artisan route:cache
            docker compose exec app php artisan view:cache

            # Corrige permissões
            docker compose exec app chown -R www-data:www-data storage bootstrap/cache
