name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/TrabalhoFinal/

            # Corrige permissões do diretório
            chmod 755 /home/ubuntu/TrabalhoFinal/

            # Marca o repositório como seguro
            git config --global --add safe.directory /home/ubuntu/TrabalhoFinal

            # Puxa alterações
            git pull

            # Cria o .env com base no secret
            echo "${{ secrets.LARAVEL_ENV }}" | tee .env > /dev/null

            # Desliga os containers
            docker compose down

            # Sobe os containers com build
            docker compose up -d --build

            # Aguarda o banco subir
            sleep 15

            # Comandos Laravel
            docker compose exec app php artisan migrate --force
            docker compose exec app php artisan optimize:clear
            docker compose exec app php artisan config:cache
            docker compose exec app php artisan route:cache
            docker compose exec app php artisan view:cache

            # Corrige permissões finais
            docker compose exec app chown -R www-data:www-data storage bootstrap/cache
